import webbrowser

def open_urls_in_browser(urls):
    for url in urls:
        webbrowser.open(url)

if __name__ == "__main__":
    urls = [
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=lighter&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=cane&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=dog cage&locations=581&locations=2&locations=653&locations=663",
"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=clippers&locations=581&locations=2&locations=653&locations=663",
"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=Shaolin&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=kung&&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=tai&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=chi&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=buddha&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=martial&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=soccer&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=sport&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=cards&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=game&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=card&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=sports&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=games&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=chinese&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=japanese&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=korean&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=knife&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=gun&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=sword&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=mlb&locations=581&locations=2&locations=653&locations=663",	
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=nfl&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=music&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=european&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=watch&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=art&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=tea&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=golf&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=remote control&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=adidas&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=nike&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=fifa&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=king mattress&locations=581&locations=2&locations=653&locations=663",
  	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=ninja&locations=581&locations=2&locations=653&locations=663",
      	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=porch swing&locations=581&locations=2&locations=653&locations=663",
       	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=metal detector&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=ice maker nugget&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=hangars&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=glasses&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=lego&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=geometry&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=new balance&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=mini fridge&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=coat&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=jacket&locations=581&locations=2&locations=653&locations=663", 
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=shelves&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=slippers&locations=581&locations=2&locations=653&locations=663",   
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=back pack&locations=581&locations=2&locations=653&locations=663",
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=f1&locations=581&locations=2&locations=653&locations=663",
	"https://www.bidfta.com/items?pageId=1&itemSearchKeywords=gaming remote&locations=581&locations=2&locations=653&locations=663", 
        "https://www.bidfta.com/items?pageId=1&itemSearchKeywords=portable clothes line&locations=581&locations=2&locations=653&locations=663"  
    ]
    open_urls_in_browser(urls)
